version: '3'
services:
  httpd:
    container_name: nginx-multidomain
    build: ./sites-available
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./sites-available/hoge.example.com.conf:/etc/nginx/sites-available/hoge.example.com.conf
      - ./sites-available/fuga.example.com.conf:/etc/nginx/sites-available/fuga.example.com.conf
    ports:
      - "8080:80"